env:
  browser: true
  node: false
  es6: true
ignorePatterns: ["js/*parser.js"]
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  array-bracket-spacing: [error, never]
  array-callback-return: error
  arrow-spacing: [error, {before: true, after: true}]
  arrow-parens:
    - error
    - as-needed
  block-spacing: error
  brace-style: [error, stroustrup]
  camelcase:
    - error
    - properties: always
      ignoreGlobals: true
      allow: [scanf_s, fscanf_s, sscanf_s, printf_s, fprintf_s, sprintf_s, snprintf_s]
  capitalized-comments: error
  comma-dangle: error
  comma-spacing: error
  comma-style: error
  consistent-return: error
  consistent-this: error
  constructor-super: error
  curly: error
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-call-spacing: error
  func-style: [error, declaration]
  getter-return: error
  indent:
    - error
    - 4
    - ignoredNodes: [ConditionalExpression]
  max-len:
    - error
    - code: 100
      tabWidth: 4
      comments: 80
      ignoreUrls: true
      ignoreStrings: false
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  no-alert: error
  no-catch-shadow: error
  no-class-assign: error
  no-compare-neg-zero: error
  no-cond-assign: error
  no-const-assign: error
  no-constant-condition: error
  no-constructor-return: error
  no-delete-var: error
  no-dupe-args: error
  no-dupe-class-members: error
  no-dupe-else-if: error
  no-dupe-keys: error
  no-duplicate-case: error
  no-duplicate-imports: error
  no-empty-character-class: error
  no-empty-pattern: error
  no-eval: error
  no-ex-assign: error
  no-extra-boolean-cast: error
  no-extra-semi: error
  no-fallthrough: error
  no-func-assign: error
  no-global-assign: error
  no-implicit-coercion: error
  no-implied-eval: error
  no-import-assign: error
  no-invalid-regexp: error
  no-invalid-this: error
  no-new: error
  no-new-native-nonconstructor: error
  no-new-symbol: error
  no-self-assign: error
  no-self-compare: error
  no-sequences:
    - error
    - allowInParentheses: true
  no-setter-return: error
  no-shadow-restricted-names: error
  no-sparse-arrays: error
  no-tabs: error
  no-this-before-super: error
  no-undef: error
  no-undef-init: error
  no-unexpected-multiline: error
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable: error
  no-unreachable-loop: error
  no-unsafe-finally: error
  no-unsafe-negation: error
  no-unused-expressions: error
  no-unused-labels: error
  no-unused-vars: error
  no-useless-return: error
  no-var: error
  prefer-const: error
  prefer-regex-literals: error
  prefer-spread: error
  quotes: [error, single]
  semi: [error, always]
  semi-spacing: error
  semi-style: error
  spaced-comment: error
  strict: [error, global]
  valid-jsdoc:
    - error
    - prefer: {return: returns}
      preferType:
        object: Object
      requireReturnDescription: false
  valid-typeof: error
  yoda: [error, never]

